title: ACBT Brochures
description: Historical brochures from Atlantic City
remote_theme: just-the-docs/just-the-docs
color_scheme: light

exclude:
  - data/*.py
  - scripts/

# Optional:
# logo: "/assets/logo.png"
# favicon_ico: "/assets/favicon.ico"

just_the_docs:
  custom_css:
    - "assets/css/custom.css"

# Enables GitHub Pages to build with this theme
plugins:
  - jekyll-remote-theme
