title: ACBT Brochures
description: Historical brochures from Atlantic City
remote_theme: just-the-docs/just-the-docs
color_scheme: light

exclude:
  - data/*.py
  - scripts/

# Optional:
# logo: "/assets/logo.png"
# favicon_ico: "/assets/favicon.ico"

just_the_docs:
  nav_external_links:
    - title: "<span class='nav-icon'>🖼️</span> Gallery"
      url: "/gallery/"
      hide_icon: true
      open_in_new_tab: false


# Enables GitHub Pages to build with this theme
plugins:
  - jekyll-remote-theme
