title: ACBT Brochures
description: Historical brochures from Atlantic City
remote_theme: just-the-docs/just-the-docs
color_scheme: light

# Optional:
# logo: "/assets/logo.png"
# favicon_ico: "/assets/favicon.ico"

# Enables GitHub Pages to build with this theme
plugins:
  - jekyll-remote-theme
